## Acrylic主题配置文件
############################################################################################################
# 为避免主题更新后，配置文件被覆盖，请复制一份此文件到站点根目录下的_config.Acrylic.yml文件中，修改_config.Acrylic.yml文件中的配置
############################################################################################################
# 修改此文件前，请仔细阅读官方文档：https://next-docs.acrylic.org.cn/
############################################################################################################


# 站点设置
site:
  name:                   # 左上角显示内容
    class:  text          #i_class/text/img
    custom: ZKHEO       #自定义内容
  siteIcon: http://blog-1256646833.cos.accelerate.myqcloud.com/avatar.gif # 网页icon
  icon: http://blog-1256646833.cos.accelerate.myqcloud.com/avatar.gif     # 页脚的icon、加载动画默认的icon
  icp:                       # ICP

# 导航栏
nav:
#导航栏左侧
  left:
    enable: true
    menu:
       我的:
         博客:
           icon: http://blog-1256646833.cos.accelerate.myqcloud.com/avatar.gif
           url: /
         GPT:
           icon: https://blog-1256646833.cos.accelerate.myqcloud.com/202305101449797.png
           url: https://gpt.zkheo.top/
# 导航栏内容
  menu:
     首页:
       url: /
     文库:
       url: false
       child:
         文章列表:
           url: /archives/
           icon: fas fa-box-archive
         全部分类:
           url: /categories/
           icon: fas fa-cube
         全部标签:
           url: /tags/
           icon: fas fa-tags
#    仓库:
#      url: https://github.com/rootlexblog
#      child:
     友链:
       url: /links/
       icon: fas fa-user-group
     关于:
       url: /about/


# 导航栏右侧快捷菜单
  right: # @todo 允许用户自定义
    travellings: true   #开往
    random: true        #随机前往一个博客
    console: true       #控制台

# heo式顶部一大坨
hometop:
  bbtime: true
  banner:
    enable: true
    title: 分享技术<br>与生活
    url: blog.zkheo.top
    icon:
      Java:
         img: https://blog-1256646833.cos.accelerate.myqcloud.com/202305101451563.png
         color: '#ffffff'
      Spring:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/202305101451265.png
        color: '#ffffff'
      Sql:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/202305101452804.png
        color: '#ffffff'
      Vue:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/202305101452496.png
        color: '#ffffff'
      HTML:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/202305101452383.png
        color: '#ffffff'
      JS:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/202305101453167.png
        color: '#ffffff'
      CSS3:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510145452.png
        color: '#ffffff'
      Python:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510145524.png
        color: '#ffffff'
      Flutter:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510145545.png
        color: '#ffffff'
      Dart:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510145610.png
        color: '#ffffff'
      Maven:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510145648.png
        color: '#ffffff'
      Git:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510145719.png
        color: '#ffffff'
      Idea:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510145736.png
        color: '#ffffff'
      Docker:
        img: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510145758.png
        color: '#ffffff'

  categoryGroup:
    G1:
      name: 热门
      icon: fas fa-dove
      url: /tags/热门/
    G2:
      name: 教程
      icon: fas fa-burn
      url: /tags/教程/
    G3:
      name: 日常
      icon: fas fa-book
      url: /tags/日常/

  recommendList:
    sup: 置顶文章
    title: ChatGPT
    url: /tags/chatGpt/
    img: https://blog-1256646833.cos.accelerate.myqcloud.com/gpt3-1024x576.png
    color: '#006a73'

# 个人卡片
aside:
  home:
    noSticky: "about,flip"
    Sticky: "newestPost,allInfo"
  post:
    noSticky: "about"
    Sticky: "newestPost"
  page:
    noSticky: "about,flip"
    Sticky: "newestPost,allInfo"

  card:
    content: 这有关于<b>开发</b>、<b>技术</b>相关的问题和看法，<br>还有一些对<b>生活</b>的记录。
    information:
      # Github:
      #   icon: fa-brands fa-github
      #   url: https://github.com/hexo-theme-Acrylic/Hexo-Theme-Acrylic-Next
       Mail:
         icon: fa-solid fa-envelope
         url: zk2252@88.com
    button:
      text: 个人主页
      url: /

  flip:
    color: '#0099FF'
    face:
      title: 微信公众号
      desc: 获取最新的文章
    backface:
      title: 扫一扫
      desc: 不错过精彩文章
      img: http://blog-1256646833.cos.accelerate.myqcloud.com/d31b0d975e89b9fd0f3b57880f67cf55.png

  toc:
    post: true
    page: false

  # 建站时间
  siteinfo:
    postcount: true
    wordcount: false
    pv: true
    uv: true
    updatetime: false
    runtimeenable: true
    runtime: '2021-12-12 00:00:00'

# 页脚
footer:
  information:
    left:
       Github:
         icon: fa-brands fa-github
         url: /
       Mail:
         icon: fa-solid fa-envelope
         url: /
    right:
       QQ:
         icon: fa-brands fa-qq
         url: /
       DOU:
         icon: fa-brands fa-tiktok
         url: /

  group:
     导航:
       文章归档: /archives/
       文章分类: /categories/
       文章标签: /tags/
       友链: /links/
     服务:
       51la统计: https://51.la/
       百度统计: https://tongji.baidu.com/
       TianliCDN: https://ql.tianli0.top/
     工具:
       ChatGPT: https://gpt.zkheo.top/

  randomlink: false

page:
  error: true
  tags: true
  categories: true
  default:
    cover: /img/hello.jpg

# 文章页默认设置
post:
  default:
    cover: /img/hello.jpg
    locate: 北京
    copyright: 原创
    excerpt: 100
  meta:
    date: true #是否显示日期
    updated: false #是否显示更新日期
    locate: false #是否显示作者IP
    wordcount: false #是否显示字数
    readtime: false #是否显示阅读时间
    pv: true #是否显示访问量
    comment: true #是否显示评论数
  award:
    enable: true #是否开启赞赏功能
    wechat: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510150034.png
    alipay: https://blog-1256646833.cos.accelerate.myqcloud.com/20230510150050.png
    url: #打赏名单url
  covercolor: #文章cover取色
    enable: false
    local: false

# 关于界面
about: true

# 404页面
errorpage:
  img: /img/hello.jpg
  text: =awa= 页面走丢了
  recommendList: true

# 懒加载
lazyload:
  enable: false
  placeholder: /img/hello.jpg
  errorimg: /img/hello.jpg

# 图片灯箱
lightbox: true

#代码高亮增强
hightlight:
  enable: false
  hightlimit: 200

# 加载动画
loading:
  fullpage: false
  pace: false

# 第三方设置
thirdparty:
  wordcount: false
  busuanzi:
    enable: true
    usecomment: false #当评论系统开启时文章页面使用评论系统的统计数据
  search:
#    algolia_search:
#      enable: false
      # hits:
      #   per_page: 6
    local_search:
      enable: true
      preload: false
      CDN:

  aplayer:
    enable: false
    server: tencent
    id: 1708664797

# 评论
comment:
  enable: true
  twikoo:
    envId: https://comment.zkheo.top
    # region: ap-shanghai
    path: window.location.pathname


# 插入代码到头部 </head> 之前 和 底部 </body> 之前
# 插入额外代码 如：统计，广告等
extends:
  head: # 在head中插入
    # - <script></script>
  body: # 在body中插入

# 非必要勿动
cdn:
  head:
    pacejs: https://lf6-cdn-tos.bytecdntp.com/cdn/expire-1-M/pace/1.2.4/pace.min.js
    fontawesomecss: https://cdn.bootcdn.net/ajax/libs/font-awesome/6.3.0/css/all.min.css
    snackbarcss: /lib/snackbar.min.css
    qrcodejs: /lib/qrcode.min.js
    twikoojs: https://cdn.staticfile.org/twikoo/1.6.10/twikoo.all.min.js
    instantsearch: https://lf26-cdn-tos.bytecdntp.com/cdn/expire-1-M/instantsearch.js/4.39.0/instantsearch.production.min.js
    algolia: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/algoliasearch/4.12.1/algoliasearch-lite.umd.min.js
  body:
    swipercss: /lib/swiper.min.css
    pjaxjs: /lib/pjax.min.js
    lazyloadjs: /lib/lazyload.min.js
    snackbarjs: /lib/snackbar.min.js
    viewimagejs: /lib/view-image.min.js
    waterfalljs: /lib/waterfall.min.js
    swiperjs: /lib/swiper.min.js
    busuanzijs: https://npm.elemecdn.com/penndu@1.0.0/bsz.js
    aplayercss: https://lf9-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.css
    aplayerjs: https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/aplayer/1.10.1/APlayer.min.js
    metingjs: https://cdn1.tianli0.top/npm/meting@2.0.1/dist/Meting.min.js
